#!/usr/bin/env bash
# gen-test-pki.sh — generate (or reuse) a local test CA + HTTPS server cert
# for the QEMU OTA fixture server, and embed the CA certificate as a C header
# (firmware/components/trust_store/include/qemu_test_ca.h) so QEMU builds can
# verify it without CONFIG_MBEDTLS_CERTIFICATE_BUNDLE. Test-only material;
# never used by board builds.
#
# Usage: ./gen-test-pki.sh
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
FW_ROOT="$(cd "$HERE/../../.." && pwd)"
PKI_DIR="$HERE/../fixtures/pki"
HEADER="$FW_ROOT/components/trust_store/include/qemu_test_ca.h"

# Guest-reachable address for QEMU user-mode networking (libslirp NAT host alias).
SLIRP_HOST_ALIAS="10.0.2.2"

mkdir -p "$PKI_DIR"
cd "$PKI_DIR"

if [[ ! -f ca_key.pem ]]; then
  openssl genrsa -out ca_key.pem 2048
  openssl req -x509 -new -key ca_key.pem -sha256 -days 3650 \
    -subj "/CN=agent-widget QEMU OTA test CA" -out ca_cert.pem
  echo "generated test CA: $PKI_DIR/ca_cert.pem"
else
  echo "reusing existing test CA: $PKI_DIR/ca_cert.pem"
fi

if [[ ! -f server_key.pem ]]; then
  openssl genrsa -out server_key.pem 2048
  cat > server_ext.cnf <<EOF
subjectAltName = IP:${SLIRP_HOST_ALIAS}, DNS:agent-widget-fixture.local, IP:127.0.0.1
EOF
  openssl req -new -key server_key.pem -subj "/CN=agent-widget-fixture" -out server.csr
  openssl x509 -req -in server.csr -CA ca_cert.pem -CAkey ca_key.pem -CAcreateserial \
    -days 3650 -sha256 -extfile server_ext.cnf -out server_cert.pem
  rm -f server.csr
  echo "generated fixture server cert: $PKI_DIR/server_cert.pem (SAN=${SLIRP_HOST_ALIAS},127.0.0.1)"
else
  echo "reusing existing fixture server cert: $PKI_DIR/server_cert.pem"
fi

python3 - "$PKI_DIR/ca_cert.pem" "$HEADER" <<'PY'
import sys

ca_path, header_path = sys.argv[1], sys.argv[2]
with open(ca_path) as f:
    pem = f.read()

lines = pem.splitlines()
c_lines = "\\n\"\n\"".join(lines)

with open(header_path, "w") as f:
    f.write("// qemu_test_ca.h — auto-generated by firmware/test/qemu/scripts/gen-test-pki.sh.\n")
    f.write("// Local test CA public certificate only (not secret); QEMU builds only.\n")
    f.write("#pragma once\n\n")
    f.write(f'static const char QEMU_TEST_CA_PEM[] =\n"{c_lines}\\n";\n')

print(f"wrote {header_path}")
PY

echo "=== test CA header ready: $HEADER (QEMU builds only; gitignored) ==="
echo "=== private keys stay local: $PKI_DIR (gitignored) ==="
