#!/usr/bin/env bash
# gen_keys.sh — generate (or reuse) a dev RSA-2048 keypair for OTA firmware signing,
# and export the public key as a C header the sketch embeds (N + E raw bytes,
# matching mbedtls_rsa_import_raw()'s expected byte order — big-endian).
#
# Private key stays under ota-sim/keys/ (gitignored, never committed).
# Usage: ./gen_keys.sh [keys_dir]
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
KEYS_DIR="${1:-$HERE/keys}"
PRIV="$KEYS_DIR/ota_dev_priv.pem"
PUB="$KEYS_DIR/ota_dev_pub.pem"
HEADER="$HERE/ota_pubkey.h"

mkdir -p "$KEYS_DIR"
if [[ -f "$PRIV" ]]; then
  echo "reusing existing key: $PRIV"
else
  openssl genrsa -out "$PRIV" 2048
  echo "generated: $PRIV"
fi
openssl rsa -in "$PRIV" -pubout -out "$PUB"

python3 - "$PUB" "$HEADER" <<'PY'
import sys, subprocess, re

pub_path, header_path = sys.argv[1], sys.argv[2]

modulus_hex = subprocess.run(
    ["openssl", "rsa", "-pubin", "-in", pub_path, "-noout", "-modulus"],
    check=True, capture_output=True, text=True
).stdout.strip()
modulus_hex = modulus_hex.split("=", 1)[1].strip()
n_bytes = bytes.fromhex(modulus_hex)
# strip a leading 0x00 sign byte if present (ASN.1 INTEGER padding for MSB=1)
if len(n_bytes) == 257 and n_bytes[0] == 0:
    n_bytes = n_bytes[1:]
assert len(n_bytes) == 256, f"expected 2048-bit modulus (256 bytes), got {len(n_bytes)}"

text = subprocess.run(
    ["openssl", "rsa", "-pubin", "-in", pub_path, "-noout", "-text"],
    check=True, capture_output=True, text=True
).stdout
m = re.search(r"Exponent:\s*(\d+)", text)
e_int = int(m.group(1))
e_bytes = e_int.to_bytes((e_int.bit_length() + 7) // 8, "big")

def carr(name, data):
    rows = []
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        rows.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    body = "\n".join(rows)
    return f"static const unsigned char {name}[{len(data)}] = {{\n{body}\n}};\n"

with open(header_path, "w") as f:
    f.write("// ota_pubkey.h — auto-generated by gen_keys.sh. Public key only (safe to commit).\n")
    f.write("// Regenerate with: ./gen_keys.sh\n")
    f.write("#pragma once\n\n")
    f.write(carr("OTA_PUBKEY_N", n_bytes))
    f.write("\n")
    f.write(carr("OTA_PUBKEY_E", e_bytes))

print(f"wrote {header_path}: N={len(n_bytes)} bytes, E={e_bytes.hex()}")
PY

echo "=== public key header ready: $HEADER (safe to commit) ==="
echo "=== private key stays local: $PRIV (gitignored) ==="
